# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abfa270e7d6e4409686020217b31ad5a9bc94379c7c22bf19decad572478a9b22710dbc6b67b889c70f8fa4d5fa62b18e6afb97ce8dd98cf8b503dc62f5cdda3

test:
  secret_key_base: ba219ecc274fd1ffa3375468c3cf59cbdcca942f0153bca9be326c0e666a3f30d57bd71f136ee6f7e13eb14b6e2494873074f26d3fe94948fef9b4a4790c56ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
